name: "nyc_taxi_analysis"
version: "1.0.0"
config-version: 2

profile: "Development"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  nyc_taxi_analysis:
    staging:
      +materialized: view
    post_staging:     
      +materialized: table
    marts:
      +materialized: table

seeds:
  nyc_taxi_analysis:   
    taxi_zone_lookup:
      +column_types:
          LocationID: NUMBER
          Borough: VARCHAR
          Zone: VARCHAR
          service_zone: VARCHAR
        

